"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowDownRight, ArrowLeft, ArrowUpRight, CalendarClock, Landmark, LoaderCircle, Pencil, Plus, Save, Trash2, WalletCards, X } from "lucide-react";
import type { AgencyClient, FinanceAccount, FinanceEntry } from "@/lib/adminData";
import styles from "../os.module.css";

type EntryForm = Omit<FinanceEntry, "id" | "created_by" | "created_by_name" | "created_at" | "updated_at"> & { id?: string };
const accountLabels: Record<FinanceAccount, string> = { bcp: "BCP", bbva: "BBVA", interbank: "Interbank", cash: "Efectivo", other: "Otra" };
async function api<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers || {}) } }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "No pudimos completar la acción."); return result as T; }
function money(value: number, currency: "PEN" | "USD") { return new Intl.NumberFormat("es-PE", { style: "currency", currency }).format(value); }
function blankEntry(clientId = ""): EntryForm { return { type: "income", date: new Date().toISOString().slice(0, 10), amount: 0, currency: "PEN", account: "bcp", category: "Mensualidad", client_id: clientId, description: "Pago de plan mensual" }; }

export default function FinanceAdmin() {
  const [entries, setEntries] = useState<FinanceEntry[]>([]); const [clients, setClients] = useState<AgencyClient[]>([]); const [form, setForm] = useState<EntryForm | null>(null); const [month, setMonth] = useState(() => new Date().toISOString().slice(0, 7)); const [currency, setCurrency] = useState<"PEN" | "USD">("PEN"); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const [openedAt] = useState(() => Date.now());
  const load = useCallback(async () => { const result = await api<{ entries: FinanceEntry[]; clients: AgencyClient[] }>("/api/admin/finance"); setEntries(result.entries); setClients(result.clients); }, []);
  useEffect(() => { let cancelled = false; void api<{ entries: FinanceEntry[]; clients: AgencyClient[] }>("/api/admin/finance").then((result) => { if (!cancelled) { setEntries(result.entries); setClients(result.clients); } }).catch((error) => { if (!cancelled) setNotice(error.message); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, []);
  const filtered = useMemo(() => entries.filter((entry) => entry.date.startsWith(month) && entry.currency === currency), [entries, month, currency]);
  const income = filtered.filter((entry) => entry.type === "income").reduce((sum, entry) => sum + entry.amount, 0); const expense = filtered.filter((entry) => entry.type === "expense").reduce((sum, entry) => sum + entry.amount, 0); const balance = income - expense;
  const expected = clients.filter((client) => client.status === "active" && client.currency === currency).reduce((sum, client) => sum + client.monthly_fee, 0);
  const byAccount = Object.keys(accountLabels).map((account) => ({ account: account as FinanceAccount, balance: filtered.filter((entry) => entry.account === account).reduce((sum, entry) => sum + (entry.type === "income" ? entry.amount : -entry.amount), 0) }));
  const expiring = clients.filter((client) => client.status === "active" && new Date(`${client.end_date}T23:59:59`).getTime() >= openedAt).toSorted((a, b) => a.end_date.localeCompare(b.end_date)).slice(0, 6);
  async function save() { if (!form) return; setBusy(true); setNotice(""); try { await api("/api/admin/finance", { method: form.id ? "PUT" : "POST", body: JSON.stringify(form) }); await load(); setForm(null); setNotice("Movimiento registrado."); } catch (error) { setNotice(error instanceof Error ? error.message : "No pudimos guardar."); } finally { setBusy(false); } }
  async function remove() { if (!form?.id || !confirm("¿Eliminar este movimiento?")) return; setBusy(true); try { await api("/api/admin/finance", { method: "DELETE", body: JSON.stringify({ id: form.id }) }); await load(); setForm(null); } finally { setBusy(false); } }
  const clientName = (id: string) => clients.find((client) => client.id === id)?.company_name || "Sin cliente";
  return <main className={styles.osPage}><header className={styles.osHeader}><div><Link href="/panel"><ArrowLeft size={17} /> Volver al panel</Link><p>CRISDAL OS · FINANZAS</p><h1>Salud financiera</h1><span>Controla ingresos, egresos, cuentas de destino y renovaciones de clientes.</span></div><button className={styles.primaryAction} onClick={() => setForm(blankEntry())}><Plus /> Registrar movimiento</button></header>
    <section className={styles.financeFilters}><label>Mes<input type="month" value={month} onChange={(event) => setMonth(event.target.value)} /></label><div className={styles.segmented}><button className={currency === "PEN" ? styles.activeSegment : ""} onClick={() => setCurrency("PEN")}>Soles</button><button className={currency === "USD" ? styles.activeSegment : ""} onClick={() => setCurrency("USD")}>Dólares</button></div></section>
    <section className={styles.financeMetrics}><article className={styles.incomeMetric}><ArrowUpRight /><span>Ingresos del mes<strong>{money(income, currency)}</strong></span></article><article className={styles.expenseMetric}><ArrowDownRight /><span>Egresos del mes<strong>{money(expense, currency)}</strong></span></article><article className={balance >= 0 ? styles.healthyMetric : styles.riskMetric}><WalletCards /><span>Saldo del mes<strong>{money(balance, currency)}</strong></span></article><article><CalendarClock /><span>Ingreso mensual esperado<strong>{money(expected, currency)}</strong></span></article></section>
    {notice ? <div className={styles.notice}>{notice}</div> : null}{loading ? <div className={styles.loadingBlock}><LoaderCircle className={styles.spin} /> Preparando finanzas…</div> : <div className={styles.financeLayout}><section><h2>Movimientos</h2><div className={styles.financeTable}>{filtered.length ? filtered.map((entry) => <button key={entry.id} onClick={() => setForm({ ...entry })}><span className={entry.type === "income" ? styles.entryIncome : styles.entryExpense}>{entry.type === "income" ? <ArrowUpRight /> : <ArrowDownRight />}</span><div><strong>{entry.description}</strong><small>{entry.date} · {clientName(entry.client_id)} · {accountLabels[entry.account]}</small></div><b>{entry.type === "income" ? "+" : "−"}{money(entry.amount, entry.currency)}</b><Pencil /></button>) : <p>No hay movimientos para este mes.</p>}</div></section><aside><h2>Saldo por cuenta</h2><div className={styles.accountStack}>{byAccount.map((item) => <article key={item.account}><Landmark /><span>{accountLabels[item.account]}<strong>{money(item.balance, currency)}</strong></span></article>)}</div><h2>Próximas renovaciones</h2><div className={styles.renewalStack}>{expiring.map((client) => <Link key={client.id} href="/panel/clientes"><span>{client.company_name}<small>{client.plan_name}</small></span><strong>{client.end_date}</strong></Link>)}</div></aside></div>}
    {form ? <div className={styles.modalBackdrop}><section className={styles.modalCard}><button className={styles.iconClose} onClick={() => setForm(null)}><X /></button><div className={styles.modalHeading}><span><WalletCards /></span><div><p>Caja y bancos</p><h2>{form.id ? "Editar movimiento" : "Nuevo movimiento"}</h2></div></div><div className={styles.formGrid}><label>Tipo<select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value as EntryForm["type"] })}><option value="income">Ingreso</option><option value="expense">Egreso</option></select></label><label>Fecha<input type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} /></label><label>Monto<input type="number" min="0.01" step="0.01" value={form.amount} onChange={(event) => setForm({ ...form, amount: Number(event.target.value) })} /></label><label>Moneda<select value={form.currency} onChange={(event) => setForm({ ...form, currency: event.target.value as EntryForm["currency"] })}><option value="PEN">Soles</option><option value="USD">Dólares</option></select></label><label>Cuenta<select value={form.account} onChange={(event) => setForm({ ...form, account: event.target.value as FinanceAccount })}>{Object.entries(accountLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Categoría<input value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })} /></label><label className={styles.fullField}>Cliente<select value={form.client_id} onChange={(event) => setForm({ ...form, client_id: event.target.value })}><option value="">Sin cliente asociado</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.company_name}</option>)}</select></label><label className={styles.fullField}>Descripción<input value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label></div><div className={styles.modalActions}>{form.id ? <button className={styles.dangerAction} onClick={() => void remove()}><Trash2 /> Eliminar</button> : null}<span /><button onClick={() => setForm(null)}>Cancelar</button><button className={styles.primaryAction} disabled={busy || !form.amount || !form.description} onClick={() => void save()}>{busy ? <LoaderCircle className={styles.spin} /> : <Save />} Guardar</button></div></section></div> : null}
  </main>;
}
