"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, BadgeCheck, Banknote, ChartNoAxesColumnIncreasing, CircleDollarSign, LoaderCircle, Pencil, Plus, Save, Trash2, TrendingUp, UserRound, X } from "lucide-react";
import type { CommissionRecord, CommissionRule, ServiceCategory } from "@/lib/adminData";
import styles from "../os.module.css";

type UserView = { id: string; displayName: string; role: string };
type ResponseData = { records: CommissionRecord[]; rules: CommissionRule[]; users: UserView[]; categories: ServiceCategory[]; currentUserId: string; canManage: boolean };
type RuleForm = Omit<CommissionRule, "created_at" | "updated_at">;
async function api<T>(init?: RequestInit): Promise<T> { const response = await fetch("/api/admin/commissions", { ...init, headers: { "Content-Type": "application/json", ...(init?.headers || {}) } }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "No pudimos completar la acción."); return result as T; }
function money(value: number) { return new Intl.NumberFormat("es-PE", { style: "currency", currency: "PEN", maximumFractionDigits: 0 }).format(value); }
function monthLabel(value: string) { return new Intl.DateTimeFormat("es-PE", { month: "short", year: "2-digit" }).format(new Date(`${value}-01T12:00:00`)); }

export default function CommissionsAdmin() {
  const [data, setData] = useState<ResponseData>({ records: [], rules: [], users: [], categories: [], currentUserId: "", canManage: false });
  const [editor, setEditor] = useState<RuleForm | null>(null);
  const [notice, setNotice] = useState("");
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const load = useCallback(async () => setData(await api<ResponseData>()), []);
  useEffect(() => { let cancelled = false; void api<ResponseData>().then((value) => { if (!cancelled) setData(value); }).catch((error) => { if (!cancelled) setNotice(error.message); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, []);
  const currentMonth = new Date().toISOString().slice(0, 7);
  const monthly = data.records.filter((record) => record.created_at.startsWith(currentMonth));
  const pending = data.records.filter((record) => record.status === "pending").reduce((sum, record) => sum + record.commission_amount, 0);
  const sold = monthly.reduce((sum, record) => sum + record.base_amount, 0);
  const earned = monthly.reduce((sum, record) => sum + record.commission_amount, 0);
  const trend = useMemo(() => Array.from({ length: 6 }, (_, index) => { const date = new Date(); date.setMonth(date.getMonth() - (5 - index)); const key = date.toISOString().slice(0, 7); return { key, value: data.records.filter((record) => record.created_at.startsWith(key)).reduce((sum, record) => sum + record.commission_amount, 0) }; }), [data.records]);
  const maxTrend = Math.max(1, ...trend.map((item) => item.value));
  function userName(id: string) { return data.users.find((user) => user.id === id)?.displayName || (id ? "Usuario" : "Todos los asesores"); }
  function categoryName(id: string) { return data.categories.find((item) => item.id === id)?.name || (id ? "Categoría" : "Todas las categorías"); }
  function createRule() { setEditor({ id: crypto.randomUUID(), user_id: "", category_id: "", commission_percent: 10, fixed_amount: 0, min_sales_threshold: 0, extra_percent_above_threshold: 0, active: true }); }
  async function saveRule() { if (!editor) return; setBusy(true); try { const exists = data.rules.some((rule) => rule.id === editor.id); const payload = { ...editor, commission_percent: Math.round(editor.commission_percent), fixed_amount: Math.round(editor.fixed_amount), min_sales_threshold: Math.round(editor.min_sales_threshold), extra_percent_above_threshold: Math.round(editor.extra_percent_above_threshold) }; const result = await api<{ rule: CommissionRule }>({ method: exists ? "PUT" : "POST", body: JSON.stringify({ action: "rule", data: payload }) }); setData((current) => ({ ...current, rules: [result.rule, ...current.rules.filter((rule) => rule.id !== result.rule.id)] })); setEditor(null); setNotice("Regla de comisión guardada y actualizada."); void load().catch(() => undefined); } catch (error) { setNotice(error instanceof Error ? error.message : "No pudimos guardar la regla."); } finally { setBusy(false); } }
  async function removeRule() { if (!editor || !data.rules.some((rule) => rule.id === editor.id) || !confirm("¿Eliminar esta regla de comisión?")) return; setBusy(true); try { await api({ method: "DELETE", body: JSON.stringify({ id: editor.id }) }); await load(); setEditor(null); setNotice("Regla eliminada."); } finally { setBusy(false); } }
  async function togglePaid(record: CommissionRecord) { setBusy(true); try { const result = await api<{ record: CommissionRecord }>({ method: "POST", body: JSON.stringify({ action: "payment", id: record.id, status: record.status === "paid" ? "pending" : "paid" }) }); setData((current) => ({ ...current, records: current.records.map((item) => item.id === result.record.id ? result.record : item) })); setNotice(record.status === "paid" ? "Comisión devuelta a pendiente." : "Comisión marcada como pagada."); void load().catch(() => undefined); } catch (error) { setNotice(error instanceof Error ? error.message : "No pudimos actualizar el pago."); } finally { setBusy(false); } }

  return <main className={styles.osPage}>
    <header className={styles.osHeader}><div><Link href="/panel/dashboard"><ArrowLeft size={17} /> Volver al dashboard</Link><p>CRISDAL OS · EQUIPO COMERCIAL</p><h1>Ventas y comisiones</h1><span>Cada cotización ganada genera su comisión de forma automática y trazable.</span></div>{data.canManage ? <button className={styles.primaryAction} onClick={createRule}><Plus /> Nueva regla</button> : null}</header>
    <section className={styles.commissionMetrics}><article><TrendingUp /><span><small>VENDIDO ESTE MES</small><strong>{money(sold)}</strong></span></article><article><CircleDollarSign /><span><small>COMISIONES DEL MES</small><strong>{money(earned)}</strong></span></article><article><Banknote /><span><small>PENDIENTE DE PAGO</small><strong>{money(pending)}</strong></span></article></section>
    {notice ? <div className={styles.notice}>{notice}</div> : null}
    {loading ? <div className={styles.loadingBlock}><LoaderCircle className={styles.spin} /> Calculando comisiones…</div> : <section className={styles.commissionLayout}><article className={styles.commissionPanel}><header><div><ChartNoAxesColumnIncreasing /><span><small>ÚLTIMOS 6 MESES</small><h2>Evolución de comisiones</h2></span></div></header><div className={styles.commissionChart}>{trend.map((item) => <div key={item.key}><span><b style={{ height: `${Math.max(5, item.value / maxTrend * 100)}%` }} /></span><strong>{money(item.value)}</strong><small>{monthLabel(item.key)}</small></div>)}</div></article><article className={styles.commissionPanel}><header><div><BadgeCheck /><span><small>REGLAS ACTIVAS</small><h2>Cómo se calcula</h2></span></div>{data.canManage ? <button onClick={createRule}><Plus /> Agregar</button> : null}</header><div className={styles.ruleList}>{data.rules.map((rule) => <button key={rule.id} onClick={() => data.canManage && setEditor({ ...rule })}><span><UserRound />{userName(rule.user_id)}<small>{categoryName(rule.category_id)}</small></span><strong>{rule.commission_percent}%{rule.fixed_amount ? ` + ${money(rule.fixed_amount)}` : ""}</strong>{data.canManage ? <Pencil /> : null}</button>)}</div>{!data.rules.length ? <p className={styles.panelEmpty}>Aún no hay reglas. Las ventas ganadas quedarán registradas con comisión S/ 0 hasta configurar una.</p> : null}</article></section>}
    {!loading ? <section className={styles.commissionHistory}><header><div><Banknote /><span><small>HISTORIAL</small><h2>Cotizaciones ganadas</h2></span></div></header><div>{data.records.map((record) => <article key={record.id}><span><strong>{record.quote_number}</strong><small>{record.user_name} · Venta {money(record.base_amount)}</small></span><span><small>{Math.round(record.commission_percent)}% + {money(record.fixed_amount)}</small><strong>{money(record.commission_amount)}</strong></span><button className={`${styles.statusPill} ${record.status === "paid" ? styles.active : styles.paused}`} disabled={!data.canManage || busy} onClick={() => void togglePaid(record)}>{record.status === "paid" ? "Pagada" : "Pendiente"}</button></article>)}</div>{!data.records.length ? <div className={styles.emptyState}><BadgeCheck /><h2>Aún no hay ventas ganadas.</h2><p>Al cambiar una cotización a “Ganada”, su comisión aparecerá aquí.</p><Link className={styles.primaryAction} href="/panel/cotizador">Ir al cotizador</Link></div> : null}</section> : null}
    {editor ? <div className={styles.modalBackdrop}><section className={styles.modalCard}><button className={styles.iconClose} onClick={() => setEditor(null)}><X /></button><div className={styles.modalHeading}><span><CircleDollarSign /></span><div><p>Regla comercial</p><h2>{data.rules.some((rule) => rule.id === editor.id) ? "Editar comisión" : "Nueva comisión"}</h2></div></div><div className={styles.formGrid}><label>Asesor<select value={editor.user_id} onChange={(event) => setEditor({ ...editor, user_id: event.target.value })}><option value="">Todos los asesores</option>{data.users.map((user) => <option key={user.id} value={user.id}>{user.displayName}</option>)}</select></label><label>Categoría<select value={editor.category_id} onChange={(event) => setEditor({ ...editor, category_id: event.target.value })}><option value="">Todas las categorías</option>{data.categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Comisión (%)<input type="number" min="0" max="100" step="1" value={editor.commission_percent || ""} placeholder="Ej. 10" onChange={(event) => setEditor({ ...editor, commission_percent: Number(event.target.value) })} /></label><label>Monto fijo por venta<input type="number" min="0" step="1" value={editor.fixed_amount || ""} placeholder="0" onChange={(event) => setEditor({ ...editor, fixed_amount: Number(event.target.value) })} /></label><label>Meta mensual para escalar<input type="number" min="0" step="1" value={editor.min_sales_threshold || ""} placeholder="Ej. 5000" onChange={(event) => setEditor({ ...editor, min_sales_threshold: Number(event.target.value) })} /></label><label>Porcentaje extra al superar meta<input type="number" min="0" max="100" step="1" value={editor.extra_percent_above_threshold || ""} placeholder="0" onChange={(event) => setEditor({ ...editor, extra_percent_above_threshold: Number(event.target.value) })} /></label><label className={styles.checkField}><input type="checkbox" checked={editor.active} onChange={(event) => setEditor({ ...editor, active: event.target.checked })} /> Regla activa</label></div><div className={styles.modalActions}>{data.rules.some((rule) => rule.id === editor.id) ? <button className={styles.dangerAction} onClick={() => void removeRule()}><Trash2 /> Eliminar</button> : null}<span /><button onClick={() => setEditor(null)}>Cancelar</button><button className={styles.primaryAction} disabled={busy} onClick={() => void saveRule()}>{busy ? <LoaderCircle className={styles.spin} /> : <Save />} Guardar regla</button></div></section></div> : null}
  </main>;
}
